 /* STEP 1
  • CREATE A SINGLE OBJECT WITH AT LEAST 3 KEY : VALUE PAIRS

  • REASIGN AT LEAST TWO VALUES
    • ONCE WITH BRACKET NOTATION 
    • ONCE WITH DOT NOTATION

  • CREATE A USER FRIENDLY STRING TEMPLATE LITERAL TO LOG OUT ALL THE VALUES TO THE CONSOLE
 */


 /* STEP 2
  • CREATE AN ARRAY OF OBJECTS (MINIMUM 5) WITH AT LEAST 3 KEY : VALUE PAIRS

  • WRITE A SIMPLE FOR LOOP TO ITERATE AND LOG OUT ELEMENTS

  • USE AN ARRAY ITERATOR TO LOG OUT THE ELEMENTS
 */


 /* STEP 3
  • USE A FOR IN LOOP TO RETURN ELEMENTS OF AN ARRAY

  • USE A FOR OF LOOP AND RETURN ALL ELEMENTS KEY AND VALUE (OBJECT)

  • USING THE SAME FOR OF LOOP LOG OUT THE VALUE OF A SINGLE KEY IN ALL ELEMENT (OBJECT)
 */
